In [89]:
#import Libraries
import urllib
import csv
from bs4 import BeautifulSoup
from urllib.request import urlopen
from urllib.request import Request, urlopen

data = []
#declare url
# urltoScrap = "https://www.cheki.com.ng/vehicles"

for i in range(33,601):

    urltoScrap = "https://www.cheki.com.ng/vehicles?page="+str(i)


    req = Request(urltoScrap, headers={'User-Agent': 'Mozilla/5.0'})

    #query the url
    page = urlopen(req).read()
    # page = urlopen(urltoScrap)

    #parse the html
    parsed_html = BeautifulSoup(page, 'html.parser')

    cars = parsed_html.find_all('li', class_ = 'listing-unit')


    for i in range(len(cars)):
        first = cars[i]

        name = first.find('div', class_ = 'listing-unit__title').text.strip()
        if (name.startswith('New')):
            name = name[4:] #Removes the \n character.

        location = first.find('div', class_ = 'listing-unit__location').text.strip()
        other_details = first.find_all('div', class_ = 'listing-unit__detail')
        price = first.find('div', class_ = 'listing-unit__price').text.strip()
        price = price[1:] #Removes the naira sign
#         Convert Price to int and remove commas
        split_price = price.split(',')
        price = ''.join(split_price)
        price = int(price)


    # print(len(other_details))

    #     If Mileage value is not available:
        if (len(other_details) >= 5):
            usedtype = other_details[0].get_text()
            year = other_details[1].get_text()
            mileage = other_details[3].get_text()
            transmission = other_details[4].get_text()
        elif(len(other_details) == 4):
            usedtype = other_details[0].get_text()
            year = other_details[1].get_text()
            mileage = ''
            transmission = other_details[3].get_text()
            
        data.append([name,location,usedtype,year,mileage,transmission,price])


# print(data)
    
myFile = open('cars_data.csv', 'w', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(data)   

print("Scrapped!!!\n")
print('Amount of data: '+str(len(data)))

Scrapped!!!

Amount of data: 11360

In [90]:
11360/20

568.0

In [91]:
568+32

600

In [92]:
myFile = open('cars_data.csv', 'a', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(data)

IndentationError: expected an indented block (<ipython-input-92-9631c8ed993a>, line 4)

In [93]:
myFile = open('cars_data.csv', 'w', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(data)

In [94]:
print('hi')

hi

In [95]:
print(len(data))

11360

In [96]:
import numpy as np

In [97]:
np_data = np.array(data)

In [98]:
np_data[1]

array(['Toyota Camry XLE V6', 'Lagos', 'Foreign Used', '2013', '',
       'Automatic', '6700000'],
      dtype='<U67')

In [100]:
np_data[0][2]

'Foreign Used'

In [108]:
new_data = []
for i in range(1,len(np_data)):
    if(np_data[i][4] != ''):
        new_data.append(np_data[i])

print(new_data)
print('len= '+str(len(new_data)))

[array(['Volkswagen LT', 'Lagos', 'Foreign Used', '1998', '280000km',
       'Manual', '2000000'],
      dtype='<U67'), array(['Acura MDX Sport Package', 'Rivers', 'Locally Used', '2007',
       '143000km', 'Automatic', '3500000'],
      dtype='<U67'), array(['Lexus ES 350', 'Delta', 'Foreign Used', '2007', '119000km',
       'Automatic', '4400000'],
      dtype='<U67'), array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2014',
       '400000km', 'Automatic', '15000000'],
      dtype='<U67'), array(['Honda Pilot EX Automatic', 'Lagos', 'Foreign Used', '2004',
       '98523km', 'Automatic', '1850000'],
      dtype='<U67'), array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2003', '120523km',
       'Automatic', '1620000'],
      dtype='<U67'), array(['Toyota Corolla 1.8 VVTL-i', 'Lagos', 'Foreign Used', '2003',
       '78024km', 'Automatic', '1880000'],
      dtype='<U67'), array(['Lexus RX 300', 'Lagos', 'Locally Used', '2000', '130234km',
       'Automatic', '1450000'],
      dtype='<U67'), array(['Toyota Sienna', 'Lagos', 'Foreign Used', '2006', '140234km',
       'Automatic', '2400000'],
      dtype='<U67'), array(['Toyota Sienna', 'Lagos', 'Foreign Used', '2004', '120345km',
       'Automatic', '2200000'],
      dtype='<U67'), array(['Toyota Corolla', 'Lagos', 'Foreign Used', '2005', '98234km',
       'Automatic', '1799999'],
      dtype='<U67'), array(['Toyota Venza', 'Lagos', 'Locally Used', '2010', '62541km',
       'Automatic', '3850000'],
      dtype='<U67'), array(['Honda Accord LX Automatic', 'Lagos', 'Locally Used', '2001',
       '168523km', 'Automatic', '520000'],
      dtype='<U67'), array(['Toyota Corolla 1.8 Sedan Automatic', 'Lagos', 'Foreign Used',
       '2012', '120021km', 'Automatic', '3450000'],
      dtype='<U67'), array(['Mercedes-Benz C350', 'Lagos', 'Locally Used', '2008', '120342km',
       'Automatic', '2800000'],
      dtype='<U67'), array(['Toyota Sienna CE', 'Lagos', 'Foreign Used', '2000', '150234km',
       'Automatic', '1350000'],
      dtype='<U67'), array(['Honda Accord Sedan EX-L', 'Lagos', 'Foreign Used', '2013',
       '29524km', 'Automatic', '5100000'],
      dtype='<U67'), array(['Toyota Corolla Automatic', 'Lagos', 'Locally Used', '2005',
       '110234km', 'Automatic', '1300000'],
      dtype='<U67'), array(['Honda Accord CrossTour EX-L AWD', 'Lagos', 'Foreign Used', '2013',
       '1km', 'Automatic', '7300000'],
      dtype='<U67'), array(['Toyota RAV4 2.0 4x4', 'Lagos', 'Foreign Used', '2006', '70000km',
       'Automatic', '2500000'],
      dtype='<U67'), array(['Ford Edge Limited AWD', 'Lagos', 'Foreign Used', '2012', '52147km',
       'Automatic', '6300000'],
      dtype='<U67'), array(['Acura ZDX', 'Lagos', 'Foreign Used', '2011', '32178km',
       'Automatic', '10500000'],
      dtype='<U67'), array(['Kia Carens 1.8 EX Automatic', 'Lagos', 'Locally Used', '2009',
       '73000km', 'Automatic', '1450000'],
      dtype='<U67'), array(['Toyota Sequoia Limited 4WD 5.7L V8', 'Lagos', 'Foreign Used',
       '2012', '25144km', 'Automatic', '9900000'],
      dtype='<U67'), array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2011',
       '1km', 'Automatic', '6750000'],
      dtype='<U67'), array(['Honda Accord Coupe EX', 'Lagos', 'Foreign Used', '2013', '1km',
       'Automatic', '5000000'],
      dtype='<U67'), array(['Toyota Highlander Limited V6', 'Lagos', 'Foreign Used', '2010',
       '1km', 'Automatic', '6700000'],
      dtype='<U67'), array(['Toyota Avalon XLE', 'Lagos', 'Foreign Used', '2008', '9km',
       'Automatic', '3000000'],
      dtype='<U67'), array(['Mercedes-Benz 814', 'Lagos', 'Foreign Used', '2000', '30000km',
       'Automatic', '3550000'],
      dtype='<U67'), array(['Toyota Corolla CE', 'Lagos', 'Foreign Used', '2007', '165863km',
       'Automatic', '2250000'],
      dtype='<U67'), array(['Honda CR-V 2.0 4WD Automatic', 'Lagos', 'Locally Used', '2000',
       '150km', 'Automatic', '650000'],
      dtype='<U67'), array(['Hyundai Accent', 'Lagos', 'Locally Used', '2014', '5000km',
       'Automatic', '2250000'],
      dtype='<U67'), array(['Honda Pilot EX 4WD Automatic', 'Abuja', 'Foreign Used', '2006',
       '95000km', 'Automatic', '1800000'],
      dtype='<U67'), array(['Honda Accord CrossTour EX-L AWD', 'Lagos', 'Foreign Used', '2013',
       '33844km', 'Automatic', '6800000'],
      dtype='<U67'), array(['Honda CR-V EX-L 4WD Automatic', 'Lagos', 'Foreign Used', '2015',
       '22903km', 'Automatic', '9800000'],
      dtype='<U67'), array(['Mercedes-Benz GLK', 'Lagos', 'Foreign Used', '2010', '42733km',
       'Automatic', '6900000'],
      dtype='<U67'), array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2009', '54632km',
       'Automatic', '4600000'],
      dtype='<U67'), array(['Lexus IS 250 SE AWD', 'Lagos', 'Foreign Used', '2006', '85638km',
       'Automatic', '3200000'],
      dtype='<U67'), array(['Honda Accord CrossTour', 'Lagos', 'Foreign Used', '2010',
       '51934km', 'Automatic', '4400000'],
      dtype='<U67'), array(['Toyota Highlander', 'Lagos', 'Foreign Used', '2010', '50394km',
       'Automatic', '6200000'],
      dtype='<U67'), array(['Toyota Corolla 1.8', 'Lagos', 'Foreign Used', '2007', '62840km',
       'Automatic', '2300000'],
      dtype='<U67'), array(['Toyota Venza LE FWD V6', 'Lagos', 'Foreign Used', '2013',
       '43748km', 'Automatic', '6800000'],
      dtype='<U67'), array(['Toyota Matrix XRS Automatic', 'Lagos', 'Foreign Used', '2004',
       '62840km', 'Automatic', '1750000'],
      dtype='<U67'), array(['Toyota Camry 3.0 V6 Automatic', 'Lagos', 'Locally Used', '2004',
       '76387km', 'Automatic', '1450000'],
      dtype='<U67'), array(['Honda Accord Coupe EX Automatic', 'Lagos', 'Locally Used', '2008',
       '118km', 'Automatic', '1650000'],
      dtype='<U67'), array(['Lexus ES 330', 'Lagos', 'Foreign Used', '2006', '115km',
       'Automatic', '2350000'],
      dtype='<U67'), array(['Mercedes-Benz C230', 'Lagos', 'Foreign Used', '2002', '100km',
       'Automatic', '2000000'],
      dtype='<U67'), array(['Mitsubishi Pajero 3.5 V6 GDI Elegance Automatic', 'Lagos',
       'Locally Used', '2003', '149km', 'Automatic', '1500000'],
      dtype='<U67'), array(['Mazda 626 1.8', 'Lagos', 'Foreign Used', '1999', '115km', 'Manual',
       '950000'],
      dtype='<U67'), array(['Toyota RAV4 Automatic', 'Lagos', 'Foreign Used', '2002', '90km',
       'Automatic', '2150000'],
      dtype='<U67'), array(['Pontiac Vibe Automatic', 'Lagos', 'Foreign Used', '2004',
       '119000km', 'Automatic', '1680000'],
      dtype='<U67'), array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2000', '121km',
       'Manual', '1050000'],
      dtype='<U67'), array(['Dodge Caliber', 'Lagos', 'Locally Used', '2007', '105km',
       'Automatic', '1200000'],
      dtype='<U67'), array(['Mercedes-Benz R Class 3.0 CDI', 'Lagos', 'Foreign Used', '2006',
       '156km', 'Automatic', '3000000'],
      dtype='<U67'), array(['Toyota Camry 3.5 XLE', 'Lagos', 'Foreign Used', '2007', '131000km',
       'Automatic', '2700000'],
      dtype='<U67'), array(['Nissan Armada Titanium', 'Lagos', 'Foreign Used', '2007', '105km',
       'Automatic', '2400000'],
      dtype='<U67'), array(['Toyota Avalon XLS', 'Lagos', 'Foreign Used', '2003', '131000km',
       'Automatic', '1650000'],
      dtype='<U67'), array(['Toyota Corolla LE Automatic', 'Lagos', 'Foreign Used', '2007',
       '108km', 'Automatic', '2200000'],
      dtype='<U67'), array(['Toyota Corolla CE', 'Lagos', 'Foreign Used', '2008', '83km',
       'Automatic', '2300000'],
      dtype='<U67'), array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2016', '12000km',
       'Automatic', '18000000'],
      dtype='<U67'), array(['Toyota Camry XLE Automatic', 'Lagos', 'Foreign Used', '2009',
       '78743km', 'Automatic', '2600000'],
      dtype='<U67'), array(['Honda Accord Coupe EX-L V-6 Automatic', 'Lagos', 'Foreign Used',
       '2013', '55909km', 'Automatic', '4300000'],
      dtype='<U67'), array(['Toyota Camry', 'Lagos', 'Foreign Used', '2008', '57000km',
       'Automatic', '2400000'],
      dtype='<U67'), array(['Toyota Matrix XR', 'Lagos', 'Locally Used', '2004', '92486km',
       'Automatic', '1320000'],
      dtype='<U67'), array(['Toyota Camry 2.4 LE', 'Lagos', 'Locally Used', '2008', '125000km',
       'Automatic', '1400000'],
      dtype='<U67'), array(['Acura TL', 'Lagos', 'Foreign Used', '2009', '71000km', 'Automatic',
       '4900000'],
      dtype='<U67'), array(['Mercedes-Benz E350', 'Lagos', 'Foreign Used', '2014', '12000km',
       'Automatic', '13500000'],
      dtype='<U67'), array(['Toyota Avensis 2.4 VVTi Executive', 'Lagos', 'Locally Used',
       '2008', '126000km', 'Automatic', '1350000'],
      dtype='<U67'), array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2006', '98088km',
       'Automatic', '1850000'],
      dtype='<U67'), array(['Toyota Camry 2.4', 'Lagos', 'Locally Used', '2008', '99786km',
       'Automatic', '1780000'],
      dtype='<U67'), array(['Mercedes-Benz ML350', 'Lagos', 'Locally Used', '2011', '52000km',
       'Automatic', '8800000'],
      dtype='<U67'), array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2008', '99087km',
       'Automatic', '2700000'],
      dtype='<U67'), array(['Toyota RAV4 2.5 Limited', 'Lagos', 'Locally Used', '2008',
       '78098km', 'Automatic', '2350000'],
      dtype='<U67'), array(['Toyota Camry SE', 'Lagos', 'Foreign Used', '2008', '65003km',
       'Automatic', '3200000'],
      dtype='<U67'), array(['Toyota Camry XLE', 'Lagos', 'Foreign Used', '2008', '55227km',
       'Automatic', '2750000'],
      dtype='<U67'), array(['Toyota Camry LE', 'Lagos', 'Foreign Used', '2013', '48592km',
       'Automatic', '5800000'],
      dtype='<U67'), array(['Toyota Highlander Limited', 'Lagos', 'Foreign Used', '2012',
       '45029km', 'Automatic', '9850000'],
      dtype='<U67'), array(['Lexus RX 300', 'Lagos', 'Foreign Used', '2000', '69140km',
       'Automatic', '2050000'],
      dtype='<U67'), array(['Lexus RX 300', 'Lagos', 'Foreign Used', '2000', '69330km',
       'Automatic', '2050000'],
      dtype='<U67'), array(['Mercedes-Benz GLK 350', 'Lagos', 'Foreign Used', '2010', '46503km',
       'Automatic', '7500000'],
      dtype='<U67'), array(['Land Rover Range Rover Sport Sport', 'Lagos', 'Foreign Used',
       '2007', '64204km', 'Automatic', '5800000'],
      dtype='<U67'), array(['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', '2008', '57839km',
       'Automatic', '5200000'],
      dtype='<U67'), array(['Toyota Venza Limited AWD V6', 'Lagos', 'Foreign Used', '2010',
       '34883km', 'Automatic', '6500000'],
      dtype='<U67'), array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2008', '48559km',
       'Automatic', '3800000'],
      dtype='<U67'), array(['Toyota Avalon XLS', 'Lagos', 'Foreign Used', '2008', '56330km',
       'Automatic', '2950000'],
      dtype='<U67'), array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2008', '58332km',
       'Automatic', '3950000'],
      dtype='<U67'), array(['Toyota Camry LE', 'Lagos', 'Foreign Used', '2009', '57829km',
       'Automatic', '2700000'],
      dtype='<U67'), array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2008', '56338km',
       'Automatic', '3300000'],
      dtype='<U67'), array(['Honda Accord', 'Lagos', 'Foreign Used', '2008', '58224km',
       'Automatic', '2700000'],
      dtype='<U67'), array(['Toyota Camry LE', 'Lagos', 'Foreign Used', '2008', '56339km',
       'Automatic', '2700000'],
      dtype='<U67'), array(['Toyota Corolla', 'Lagos', 'Foreign Used', '2006', '58224km',
       'Automatic', '2400000'],
      dtype='<U67'), array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2008', '58229km',
       'Automatic', '3800000'],
      dtype='<U67'), array(['Toyota Corolla LE 4-Speed Aut', 'Lagos', 'Foreign Used', '2010',
       '59000km', 'Automatic', '3300000'],
      dtype='<U67'), array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2007', '92000km',
       'Automatic', '3400000'],
      dtype='<U67'), array(['Toyota Yaris', 'Lagos', 'Foreign Used', '2008', '67830km',
       'Automatic', '2350000'],
      dtype='<U67'), array(['Toyota Camry', 'Lagos', 'Foreign Used', '2004', '76467km',
       'Automatic', '1690000'],
      dtype='<U67'), array(['Toyota Camry SE V6 Automatic', 'Lagos', 'Foreign Used', '2008',
       '87689km', 'Automatic', '2350000'],
      dtype='<U67'), array(['Honda Pilot', 'Lagos', 'Foreign Used', '2004', '78302km',
       'Automatic', '1670000'],
      dtype='<U67'), array(['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', '2006', '165263km',
       'Automatic', '4480000'],
      dtype='<U67'), array(['Toyota Camry LE', 'Lagos', 'Foreign Used', '2011', '1km',
       'Automatic', '3000000'],
      dtype='<U67'), array(['Honda Accord EX', 'Lagos', 'Foreign Used', '2011', '1km',
       'Automatic', '3200000'],
      dtype='<U67'), array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2015', '1km',
       'Automatic', '18000000'],
      dtype='<U67'), array(['Hyundai ix35 1.6', 'Lagos', 'Locally Used', '2012', '1km',
       'Automatic', '3300000'],
      dtype='<U67'), array(['Toyota Venza XLE AWD V6', 'Lagos', 'Foreign Used', '2013', '1km',
       'Automatic', '8100000'],
      dtype='<U67'), array(['Honda Accord CrossTour EX-L AWD', 'Lagos', 'Foreign Used', '2011',
       '1km', 'Automatic', '4700000'],
      dtype='<U67'), array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2013', '1km',
       'Automatic', '7700000'],
      dtype='<U67'), array(['Lexus RX 350 AWD', 'Lagos', 'Foreign Used', '2015', '1km',
       'Automatic', '12500000'],
      dtype='<U67'), array(['Honda Accord EX', 'Lagos', 'Foreign Used', '2013', '1km',
       'Automatic', '5400000'],
      dtype='<U67'), array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2011',
       '1km', 'Automatic', '7600000'],
      dtype='<U67'), array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2010',
       '1km', 'Automatic', '7600000'],
      dtype='<U67'), array(['Lexus RX 350 AWD', 'Lagos', 'Foreign Used', '2015', '1km',
       'Automatic', '13500000'],
      dtype='<U67'), array(['Pontiac Vibe 1.8 Automatic', 'Lagos', 'Locally Used', '2004',
       '1km', 'Automatic', '1300000'],
      dtype='<U67'), array(['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', '2012', '1km',
       'Automatic', '13500000'],
      dtype='<U67'), array(['Toyota Corolla S', 'Lagos', 'Foreign Used', '2014', '1km',
       'Automatic', '5700000'],
      dtype='<U67'), array(['Hyundai ix35', 'Lagos', 'Locally Used', '2013', '1km', 'Automatic',
       '3600000'],
      dtype='<U67'), array(['Toyota 4-Runner', 'Lagos', 'Foreign Used', '2013', '6365km',
       'Automatic', '14500000'],
      dtype='<U67'), array(['Toyota Land Cruiser 100 4.7 V8 Executive', 'Lagos', 'Foreign Used',
       '2008', '3457km', 'Automatic', '19000000'],
      dtype='<U67'), array(['Land Rover Range Rover Sport', 'Lagos', 'Foreign Used', '2010',
       '34068km', 'Automatic', '13500000'],
      dtype='<U67'), array(['Toyota Venza V6', 'Lagos', 'Foreign Used', '2013', '3457km',
       'Automatic', '9000000'],
      dtype='<U67'), array(['Lexus LX 570', 'Lagos', 'Foreign Used', '2015', '3457km',
       'Automatic', '32000000'],
      dtype='<U67'), array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2014',
       '20042km', 'Automatic', '14800000'],
      dtype='<U67'), array(['Toyota Hilux 2.7 VVTI 4x2 Single Cab', 'Lagos', 'Foreign Used',
       '2012', '125943km', 'Manual', '14000000'],
      dtype='<U67'), array(['Mercedes-Benz C240', 'Lagos', 'Foreign Used', '2002', '96437km',
       'Automatic', '2800000'],
      dtype='<U67'), array(['Nissan Pathfinder LE 4x4', 'Lagos', 'Foreign Used', '2006',
       '80000km', 'Automatic', '2500000'],
      dtype='<U67'), array(['Honda Pilot EX 4WD Automatic', 'Lagos', 'Foreign Used', '2004',
       '90000km', 'Automatic', '1800000'],
      dtype='<U67'), array(['Honda CR-V 2.0 4WD Automatic', 'Lagos', 'Foreign Used', '2005',
       '80000km', 'Automatic', '1650000'],
      dtype='<U67'), array(['Land Rover Range Rover Evoque', 'Lagos', 'Foreign Used', '2014',
       '6554km', 'Automatic', '17500000'],
      dtype='<U67'), array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2009', '67542km',
       'Automatic', '3550000'],
      dtype='<U67'), array(['Toyota Corolla S Automatic', 'Lagos', 'Foreign Used', '2010',
       '68427km', 'Automatic', '3300000'],
      dtype='<U67'), array(['Toyota 4-Runner', 'Lagos', 'Locally Used', '2007', '78742km',
       'Automatic', '2480000'],
      dtype='<U67'), array(['Lexus ES 300', 'Lagos', 'Foreign Used', '2004', '69872km',
       'Automatic', '2280000'],
      dtype='<U67'), array(['Toyota Sienna LE 7 Passenger Mobility', 'Lagos', 'Foreign Used',
       '2008', '68752km', 'Automatic', '2700000'],
      dtype='<U67'), array(['Honda Pilot EX 4WD Automatic', 'Lagos', 'Foreign Used', '2008',
       '68572km', 'Automatic', '3200000'],
      dtype='<U67'), array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2010', '67748km',
       'Automatic', '3500000'],
      dtype='<U67'), array(['Lexus RX 3.3 Auto', 'Lagos', 'Foreign Used', '2009', '41752km',
       'Automatic', '5450000'],
      dtype='<U67'), array(['Honda Accord EX V6 Automatic', 'Lagos', 'Foreign Used', '2009',
       '100246km', 'Automatic', '2650000'],
      dtype='<U67'), array(['Honda Accord', 'Lagos', 'Foreign Used', '2013', '63394km',
       'Automatic', '5000000'],
      dtype='<U67'), array(['Toyota Highlander Limited V6 4x4', 'Lagos', 'Foreign Used', '2006',
       '698742km', 'Automatic', '2800000'],
      dtype='<U67'), array(['Mercedes-Benz CLA-Class', 'Lagos', 'Foreign Used', '2014',
       '69000km', 'Automatic', '14500000'],
      dtype='<U67'), array(['Mercedes-Benz ML350', 'Lagos', 'Locally Used', '2013', '85000km',
       'Automatic', '9800000'],
      dtype='<U67'), array(['Toyota Highlander Limited 4x4', 'Lagos', 'Foreign Used', '2013',
       '53000km', 'Automatic', '10500000'],
      dtype='<U67'), array(['Toyota RAV4 2.5 Limited 4x4', 'Lagos', 'Foreign Used', '2017',
       '35946km', 'Automatic', '13800000'],
      dtype='<U67'), array(['Land Rover Range Rover Vogue', 'Lagos', 'Locally Used', '2014',
       '25000km', 'Automatic', '42500000'],
      dtype='<U67'), array(['Toyota Venza Limited AWD V6', 'Lagos', 'Locally Used', '2010',
       '54253km', 'Automatic', '4500000'],
      dtype='<U67'), array(['BMW X6 xDrive 35i', 'Lagos', 'Locally Used', '2012', '82000km',
       'Automatic', '6850000'],
      dtype='<U67'), array(['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', '2013', '39594km',
       'Automatic', '12500000'],
      dtype='<U67'), array(['Mercedes-Benz GLE', 'Lagos', 'Foreign Used', '2016', '17299km',
       'Automatic', '36800000'],
      dtype='<U67'), array(['Lexus RX 400h', 'Lagos', 'Foreign Used', '2010', '64000km',
       'Automatic', '5900000'],
      dtype='<U67'), array(['Toyota Highlander V6', 'Lagos', 'Foreign Used', '2013', '45726km',
       'Automatic', '9500000'],
      dtype='<U67'), array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2008', '119115km',
       'Automatic', '5500000'],
      dtype='<U67'), array(['Cadillac Escalade', 'Lagos', 'Foreign Used', '2015', '53726km',
       'Automatic', '28000000'],
      dtype='<U67'), array(['Toyota Corolla 1.8', 'Lagos', 'Brand New', '2017', '1600km',
       'Automatic', '11500000'],
      dtype='<U67'), array(['Land Rover Range Rover Vogue', 'Lagos', 'Locally Used', '2014',
       '24000km', 'Automatic', '33000000'],
      dtype='<U67'), array(['Land Rover Range Rover Sport', 'Lagos', 'Foreign Used', '2011',
       '63217km', 'Automatic', '13500000'],
      dtype='<U67'), array(['Toyota RAV4', 'Lagos', 'Foreign Used', '2002', '101780km',
       'Automatic', '1500000'],
      dtype='<U67'), array(['Toyota Highlander', 'Lagos', 'Foreign Used', '2014', '15000km',
       'Automatic', '14200000'],

In [109]:
myFile = open('new_cars_data.csv', 'w', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(new_data)

In [110]:
unique,pos = np.unique(new_data,return_inverse=True) #Finds all unique elements and their positions
counts = np.bincount(pos)                     #Count the number of each unique element
maxpos = counts.argmax()                      #Finds the positions of the maximum count

print(unique[maxpos],counts[maxpos])

Automatic 2790

In [117]:
new_data[:,0]

TypeError: list indices must be integers or slices, not tuple

In [122]:
str_sam = "10000km"

In [123]:
int(str_sam[:-2])

10000

In [127]:
new_data

[array(['Volkswagen LT', 'Lagos', 'Foreign Used', '1998', '280000km',
        'Manual', '2000000'],
       dtype='<U67'),
 array(['Acura MDX Sport Package', 'Rivers', 'Locally Used', '2007',
        '143000km', 'Automatic', '3500000'],
       dtype='<U67'),
 array(['Lexus ES 350', 'Delta', 'Foreign Used', '2007', '119000km',
        'Automatic', '4400000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2014',
        '400000km', 'Automatic', '15000000'],
       dtype='<U67'),
 array(['Honda Pilot EX Automatic', 'Lagos', 'Foreign Used', '2004',
        '98523km', 'Automatic', '1850000'],
       dtype='<U67'),
 array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2003', '120523km',
        'Automatic', '1620000'],
       dtype='<U67'),
 array(['Toyota Corolla 1.8 VVTL-i', 'Lagos', 'Foreign Used', '2003',
        '78024km', 'Automatic', '1880000'],
       dtype='<U67'),
 array(['Lexus RX 300', 'Lagos', 'Locally Used', '2000', '130234km',
        'Automatic', '1450000'],
       dtype='<U67'),
 array(['Toyota Sienna', 'Lagos', 'Foreign Used', '2006', '140234km',
        'Automatic', '2400000'],
       dtype='<U67'),
 array(['Toyota Sienna', 'Lagos', 'Foreign Used', '2004', '120345km',
        'Automatic', '2200000'],
       dtype='<U67'),
 array(['Toyota Corolla', 'Lagos', 'Foreign Used', '2005', '98234km',
        'Automatic', '1799999'],
       dtype='<U67'),
 array(['Toyota Venza', 'Lagos', 'Locally Used', '2010', '62541km',
        'Automatic', '3850000'],
       dtype='<U67'),
 array(['Honda Accord LX Automatic', 'Lagos', 'Locally Used', '2001',
        '168523km', 'Automatic', '520000'],
       dtype='<U67'),
 array(['Toyota Corolla 1.8 Sedan Automatic', 'Lagos', 'Foreign Used',
        '2012', '120021km', 'Automatic', '3450000'],
       dtype='<U67'),
 array(['Mercedes-Benz C350', 'Lagos', 'Locally Used', '2008', '120342km',
        'Automatic', '2800000'],
       dtype='<U67'),
 array(['Toyota Sienna CE', 'Lagos', 'Foreign Used', '2000', '150234km',
        'Automatic', '1350000'],
       dtype='<U67'),
 array(['Honda Accord Sedan EX-L', 'Lagos', 'Foreign Used', '2013',
        '29524km', 'Automatic', '5100000'],
       dtype='<U67'),
 array(['Toyota Corolla Automatic', 'Lagos', 'Locally Used', '2005',
        '110234km', 'Automatic', '1300000'],
       dtype='<U67'),
 array(['Honda Accord CrossTour EX-L AWD', 'Lagos', 'Foreign Used', '2013',
        '1km', 'Automatic', '7300000'],
       dtype='<U67'),
 array(['Toyota RAV4 2.0 4x4', 'Lagos', 'Foreign Used', '2006', '70000km',
        'Automatic', '2500000'],
       dtype='<U67'),
 array(['Ford Edge Limited AWD', 'Lagos', 'Foreign Used', '2012', '52147km',
        'Automatic', '6300000'],
       dtype='<U67'),
 array(['Acura ZDX', 'Lagos', 'Foreign Used', '2011', '32178km',
        'Automatic', '10500000'],
       dtype='<U67'),
 array(['Kia Carens 1.8 EX Automatic', 'Lagos', 'Locally Used', '2009',
        '73000km', 'Automatic', '1450000'],
       dtype='<U67'),
 array(['Toyota Sequoia Limited 4WD 5.7L V8', 'Lagos', 'Foreign Used',
        '2012', '25144km', 'Automatic', '9900000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2011',
        '1km', 'Automatic', '6750000'],
       dtype='<U67'),
 array(['Honda Accord Coupe EX', 'Lagos', 'Foreign Used', '2013', '1km',
        'Automatic', '5000000'],
       dtype='<U67'),
 array(['Toyota Highlander Limited V6', 'Lagos', 'Foreign Used', '2010',
        '1km', 'Automatic', '6700000'],
       dtype='<U67'),
 array(['Toyota Avalon XLE', 'Lagos', 'Foreign Used', '2008', '9km',
        'Automatic', '3000000'],
       dtype='<U67'),
 array(['Mercedes-Benz 814', 'Lagos', 'Foreign Used', '2000', '30000km',
        'Automatic', '3550000'],
       dtype='<U67'),
 array(['Toyota Corolla CE', 'Lagos', 'Foreign Used', '2007', '165863km',
        'Automatic', '2250000'],
       dtype='<U67'),
 array(['Honda CR-V 2.0 4WD Automatic', 'Lagos', 'Locally Used', '2000',
        '150km', 'Automatic', '650000'],
       dtype='<U67'),
 array(['Hyundai Accent', 'Lagos', 'Locally Used', '2014', '5000km',
        'Automatic', '2250000'],
       dtype='<U67'),
 array(['Honda Pilot EX 4WD Automatic', 'Abuja', 'Foreign Used', '2006',
        '95000km', 'Automatic', '1800000'],
       dtype='<U67'),
 array(['Honda Accord CrossTour EX-L AWD', 'Lagos', 'Foreign Used', '2013',
        '33844km', 'Automatic', '6800000'],
       dtype='<U67'),
 array(['Honda CR-V EX-L 4WD Automatic', 'Lagos', 'Foreign Used', '2015',
        '22903km', 'Automatic', '9800000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLK', 'Lagos', 'Foreign Used', '2010', '42733km',
        'Automatic', '6900000'],
       dtype='<U67'),
 array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2009', '54632km',
        'Automatic', '4600000'],
       dtype='<U67'),
 array(['Lexus IS 250 SE AWD', 'Lagos', 'Foreign Used', '2006', '85638km',
        'Automatic', '3200000'],
       dtype='<U67'),
 array(['Honda Accord CrossTour', 'Lagos', 'Foreign Used', '2010',
        '51934km', 'Automatic', '4400000'],
       dtype='<U67'),
 array(['Toyota Highlander', 'Lagos', 'Foreign Used', '2010', '50394km',
        'Automatic', '6200000'],
       dtype='<U67'),
 array(['Toyota Corolla 1.8', 'Lagos', 'Foreign Used', '2007', '62840km',
        'Automatic', '2300000'],
       dtype='<U67'),
 array(['Toyota Venza LE FWD V6', 'Lagos', 'Foreign Used', '2013',
        '43748km', 'Automatic', '6800000'],
       dtype='<U67'),
 array(['Toyota Matrix XRS Automatic', 'Lagos', 'Foreign Used', '2004',
        '62840km', 'Automatic', '1750000'],
       dtype='<U67'),
 array(['Toyota Camry 3.0 V6 Automatic', 'Lagos', 'Locally Used', '2004',
        '76387km', 'Automatic', '1450000'],
       dtype='<U67'),
 array(['Honda Accord Coupe EX Automatic', 'Lagos', 'Locally Used', '2008',
        '118km', 'Automatic', '1650000'],
       dtype='<U67'),
 array(['Lexus ES 330', 'Lagos', 'Foreign Used', '2006', '115km',
        'Automatic', '2350000'],
       dtype='<U67'),
 array(['Mercedes-Benz C230', 'Lagos', 'Foreign Used', '2002', '100km',
        'Automatic', '2000000'],
       dtype='<U67'),
 array(['Mitsubishi Pajero 3.5 V6 GDI Elegance Automatic', 'Lagos',
        'Locally Used', '2003', '149km', 'Automatic', '1500000'],
       dtype='<U67'),
 array(['Mazda 626 1.8', 'Lagos', 'Foreign Used', '1999', '115km', 'Manual',
        '950000'],
       dtype='<U67'),
 array(['Toyota RAV4 Automatic', 'Lagos', 'Foreign Used', '2002', '90km',
        'Automatic', '2150000'],
       dtype='<U67'),
 array(['Pontiac Vibe Automatic', 'Lagos', 'Foreign Used', '2004',
        '119000km', 'Automatic', '1680000'],
       dtype='<U67'),
 array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2000', '121km',
        'Manual', '1050000'],
       dtype='<U67'),
 array(['Dodge Caliber', 'Lagos', 'Locally Used', '2007', '105km',
        'Automatic', '1200000'],
       dtype='<U67'),
 array(['Mercedes-Benz R Class 3.0 CDI', 'Lagos', 'Foreign Used', '2006',
        '156km', 'Automatic', '3000000'],
       dtype='<U67'),
 array(['Toyota Camry 3.5 XLE', 'Lagos', 'Foreign Used', '2007', '131000km',
        'Automatic', '2700000'],
       dtype='<U67'),
 array(['Nissan Armada Titanium', 'Lagos', 'Foreign Used', '2007', '105km',
        'Automatic', '2400000'],
       dtype='<U67'),
 array(['Toyota Avalon XLS', 'Lagos', 'Foreign Used', '2003', '131000km',
        'Automatic', '1650000'],
       dtype='<U67'),
 array(['Toyota Corolla LE Automatic', 'Lagos', 'Foreign Used', '2007',
        '108km', 'Automatic', '2200000'],
       dtype='<U67'),
 array(['Toyota Corolla CE', 'Lagos', 'Foreign Used', '2008', '83km',
        'Automatic', '2300000'],
       dtype='<U67'),
 array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2016', '12000km',
        'Automatic', '18000000'],
       dtype='<U67'),
 array(['Toyota Camry XLE Automatic', 'Lagos', 'Foreign Used', '2009',
        '78743km', 'Automatic', '2600000'],
       dtype='<U67'),
 array(['Honda Accord Coupe EX-L V-6 Automatic', 'Lagos', 'Foreign Used',
        '2013', '55909km', 'Automatic', '4300000'],
       dtype='<U67'),
 array(['Toyota Camry', 'Lagos', 'Foreign Used', '2008', '57000km',
        'Automatic', '2400000'],
       dtype='<U67'),
 array(['Toyota Matrix XR', 'Lagos', 'Locally Used', '2004', '92486km',
        'Automatic', '1320000'],
       dtype='<U67'),
 array(['Toyota Camry 2.4 LE', 'Lagos', 'Locally Used', '2008', '125000km',
        'Automatic', '1400000'],
       dtype='<U67'),
 array(['Acura TL', 'Lagos', 'Foreign Used', '2009', '71000km', 'Automatic',
        '4900000'],
       dtype='<U67'),
 array(['Mercedes-Benz E350', 'Lagos', 'Foreign Used', '2014', '12000km',
        'Automatic', '13500000'],
       dtype='<U67'),
 array(['Toyota Avensis 2.4 VVTi Executive', 'Lagos', 'Locally Used',
        '2008', '126000km', 'Automatic', '1350000'],
       dtype='<U67'),
 array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2006', '98088km',
        'Automatic', '1850000'],
       dtype='<U67'),
 array(['Toyota Camry 2.4', 'Lagos', 'Locally Used', '2008', '99786km',
        'Automatic', '1780000'],
       dtype='<U67'),
 array(['Mercedes-Benz ML350', 'Lagos', 'Locally Used', '2011', '52000km',
        'Automatic', '8800000'],
       dtype='<U67'),
 array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2008', '99087km',
        'Automatic', '2700000'],
       dtype='<U67'),
 array(['Toyota RAV4 2.5 Limited', 'Lagos', 'Locally Used', '2008',
        '78098km', 'Automatic', '2350000'],
       dtype='<U67'),
 array(['Toyota Camry SE', 'Lagos', 'Foreign Used', '2008', '65003km',
        'Automatic', '3200000'],
       dtype='<U67'),
 array(['Toyota Camry XLE', 'Lagos', 'Foreign Used', '2008', '55227km',
        'Automatic', '2750000'],
       dtype='<U67'),
 array(['Toyota Camry LE', 'Lagos', 'Foreign Used', '2013', '48592km',
        'Automatic', '5800000'],
       dtype='<U67'),
 array(['Toyota Highlander Limited', 'Lagos', 'Foreign Used', '2012',
        '45029km', 'Automatic', '9850000'],
       dtype='<U67'),
 array(['Lexus RX 300', 'Lagos', 'Foreign Used', '2000', '69140km',
        'Automatic', '2050000'],
       dtype='<U67'),
 array(['Lexus RX 300', 'Lagos', 'Foreign Used', '2000', '69330km',
        'Automatic', '2050000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLK 350', 'Lagos', 'Foreign Used', '2010', '46503km',
        'Automatic', '7500000'],
       dtype='<U67'),
 array(['Land Rover Range Rover Sport Sport', 'Lagos', 'Foreign Used',
        '2007', '64204km', 'Automatic', '5800000'],
       dtype='<U67'),
 array(['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', '2008', '57839km',
        'Automatic', '5200000'],
       dtype='<U67'),
 array(['Toyota Venza Limited AWD V6', 'Lagos', 'Foreign Used', '2010',
        '34883km', 'Automatic', '6500000'],
       dtype='<U67'),
 array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2008', '48559km',
        'Automatic', '3800000'],
       dtype='<U67'),
 array(['Toyota Avalon XLS', 'Lagos', 'Foreign Used', '2008', '56330km',
        'Automatic', '2950000'],
       dtype='<U67'),
 array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2008', '58332km',
        'Automatic', '3950000'],
       dtype='<U67'),
 array(['Toyota Camry LE', 'Lagos', 'Foreign Used', '2009', '57829km',
        'Automatic', '2700000'],
       dtype='<U67'),
 array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2008', '56338km',
        'Automatic', '3300000'],
       dtype='<U67'),
 array(['Honda Accord', 'Lagos', 'Foreign Used', '2008', '58224km',
        'Automatic', '2700000'],
       dtype='<U67'),
 array(['Toyota Camry LE', 'Lagos', 'Foreign Used', '2008', '56339km',
        'Automatic', '2700000'],
       dtype='<U67'),
 array(['Toyota Corolla', 'Lagos', 'Foreign Used', '2006', '58224km',
        'Automatic', '2400000'],
       dtype='<U67'),
 array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2008', '58229km',
        'Automatic', '3800000'],
       dtype='<U67'),
 array(['Toyota Corolla LE 4-Speed Aut', 'Lagos', 'Foreign Used', '2010',
        '59000km', 'Automatic', '3300000'],
       dtype='<U67'),
 array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2007', '92000km',
        'Automatic', '3400000'],
       dtype='<U67'),
 array(['Toyota Yaris', 'Lagos', 'Foreign Used', '2008', '67830km',
        'Automatic', '2350000'],
       dtype='<U67'),
 array(['Toyota Camry', 'Lagos', 'Foreign Used', '2004', '76467km',
        'Automatic', '1690000'],
       dtype='<U67'),
 array(['Toyota Camry SE V6 Automatic', 'Lagos', 'Foreign Used', '2008',
        '87689km', 'Automatic', '2350000'],
       dtype='<U67'),
 array(['Honda Pilot', 'Lagos', 'Foreign Used', '2004', '78302km',
        'Automatic', '1670000'],
       dtype='<U67'),
 array(['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', '2006', '165263km',
        'Automatic', '4480000'],
       dtype='<U67'),
 array(['Toyota Camry LE', 'Lagos', 'Foreign Used', '2011', '1km',
        'Automatic', '3000000'],
       dtype='<U67'),
 array(['Honda Accord EX', 'Lagos', 'Foreign Used', '2011', '1km',
        'Automatic', '3200000'],
       dtype='<U67'),
 array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2015', '1km',
        'Automatic', '18000000'],
       dtype='<U67'),
 array(['Hyundai ix35 1.6', 'Lagos', 'Locally Used', '2012', '1km',
        'Automatic', '3300000'],
       dtype='<U67'),
 array(['Toyota Venza XLE AWD V6', 'Lagos', 'Foreign Used', '2013', '1km',
        'Automatic', '8100000'],
       dtype='<U67'),
 array(['Honda Accord CrossTour EX-L AWD', 'Lagos', 'Foreign Used', '2011',
        '1km', 'Automatic', '4700000'],
       dtype='<U67'),
 array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2013', '1km',
        'Automatic', '7700000'],
       dtype='<U67'),
 array(['Lexus RX 350 AWD', 'Lagos', 'Foreign Used', '2015', '1km',
        'Automatic', '12500000'],
       dtype='<U67'),
 array(['Honda Accord EX', 'Lagos', 'Foreign Used', '2013', '1km',
        'Automatic', '5400000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2011',
        '1km', 'Automatic', '7600000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2010',
        '1km', 'Automatic', '7600000'],
       dtype='<U67'),
 array(['Lexus RX 350 AWD', 'Lagos', 'Foreign Used', '2015', '1km',
        'Automatic', '13500000'],
       dtype='<U67'),
 array(['Pontiac Vibe 1.8 Automatic', 'Lagos', 'Locally Used', '2004',
        '1km', 'Automatic', '1300000'],
       dtype='<U67'),
 array(['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', '2012', '1km',
        'Automatic', '13500000'],
       dtype='<U67'),
 array(['Toyota Corolla S', 'Lagos', 'Foreign Used', '2014', '1km',
        'Automatic', '5700000'],
       dtype='<U67'),
 array(['Hyundai ix35', 'Lagos', 'Locally Used', '2013', '1km', 'Automatic',
        '3600000'],
       dtype='<U67'),
 array(['Toyota 4-Runner', 'Lagos', 'Foreign Used', '2013', '6365km',
        'Automatic', '14500000'],
       dtype='<U67'),
 array(['Toyota Land Cruiser 100 4.7 V8 Executive', 'Lagos', 'Foreign Used',
        '2008', '3457km', 'Automatic', '19000000'],
       dtype='<U67'),
 array(['Land Rover Range Rover Sport', 'Lagos', 'Foreign Used', '2010',
        '34068km', 'Automatic', '13500000'],
       dtype='<U67'),
 array(['Toyota Venza V6', 'Lagos', 'Foreign Used', '2013', '3457km',
        'Automatic', '9000000'],
       dtype='<U67'),
 array(['Lexus LX 570', 'Lagos', 'Foreign Used', '2015', '3457km',
        'Automatic', '32000000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2014',
        '20042km', 'Automatic', '14800000'],
       dtype='<U67'),
 array(['Toyota Hilux 2.7 VVTI 4x2 Single Cab', 'Lagos', 'Foreign Used',
        '2012', '125943km', 'Manual', '14000000'],
       dtype='<U67'),
 array(['Mercedes-Benz C240', 'Lagos', 'Foreign Used', '2002', '96437km',
        'Automatic', '2800000'],
       dtype='<U67'),
 array(['Nissan Pathfinder LE 4x4', 'Lagos', 'Foreign Used', '2006',
        '80000km', 'Automatic', '2500000'],
       dtype='<U67'),
 array(['Honda Pilot EX 4WD Automatic', 'Lagos', 'Foreign Used', '2004',
        '90000km', 'Automatic', '1800000'],
       dtype='<U67'),
 array(['Honda CR-V 2.0 4WD Automatic', 'Lagos', 'Foreign Used', '2005',
        '80000km', 'Automatic', '1650000'],
       dtype='<U67'),
 array(['Land Rover Range Rover Evoque', 'Lagos', 'Foreign Used', '2014',
        '6554km', 'Automatic', '17500000'],
       dtype='<U67'),
 array(['Lexus ES 350', 'Lagos', 'Foreign Used', '2009', '67542km',
        'Automatic', '3550000'],
       dtype='<U67'),
 array(['Toyota Corolla S Automatic', 'Lagos', 'Foreign Used', '2010',
        '68427km', 'Automatic', '3300000'],
       dtype='<U67'),
 array(['Toyota 4-Runner', 'Lagos', 'Locally Used', '2007', '78742km',
        'Automatic', '2480000'],
       dtype='<U67'),
 array(['Lexus ES 300', 'Lagos', 'Foreign Used', '2004', '69872km',
        'Automatic', '2280000'],
       dtype='<U67'),
 array(['Toyota Sienna LE 7 Passenger Mobility', 'Lagos', 'Foreign Used',
        '2008', '68752km', 'Automatic', '2700000'],
       dtype='<U67'),
 array(['Honda Pilot EX 4WD Automatic', 'Lagos', 'Foreign Used', '2008',
        '68572km', 'Automatic', '3200000'],
       dtype='<U67'),
 array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2010', '67748km',
        'Automatic', '3500000'],
       dtype='<U67'),
 array(['Lexus RX 3.3 Auto', 'Lagos', 'Foreign Used', '2009', '41752km',
        'Automatic', '5450000'],
       dtype='<U67'),
 array(['Honda Accord EX V6 Automatic', 'Lagos', 'Foreign Used', '2009',
        '100246km', 'Automatic', '2650000'],
       dtype='<U67'),
 array(['Honda Accord', 'Lagos', 'Foreign Used', '2013', '63394km',
        'Automatic', '5000000'],
       dtype='<U67'),
 array(['Toyota Highlander Limited V6 4x4', 'Lagos', 'Foreign Used', '2006',
        '698742km', 'Automatic', '2800000'],
       dtype='<U67'),
 array(['Mercedes-Benz CLA-Class', 'Lagos', 'Foreign Used', '2014',
        '69000km', 'Automatic', '14500000'],
       dtype='<U67'),
 array(['Mercedes-Benz ML350', 'Lagos', 'Locally Used', '2013', '85000km',
        'Automatic', '9800000'],
       dtype='<U67'),
 array(['Toyota Highlander Limited 4x4', 'Lagos', 'Foreign Used', '2013',
        '53000km', 'Automatic', '10500000'],
       dtype='<U67'),
 array(['Toyota RAV4 2.5 Limited 4x4', 'Lagos', 'Foreign Used', '2017',
        '35946km', 'Automatic', '13800000'],
       dtype='<U67'),
 array(['Land Rover Range Rover Vogue', 'Lagos', 'Locally Used', '2014',
        '25000km', 'Automatic', '42500000'],
       dtype='<U67'),
 array(['Toyota Venza Limited AWD V6', 'Lagos', 'Locally Used', '2010',
        '54253km', 'Automatic', '4500000'],
       dtype='<U67'),
 array(['BMW X6 xDrive 35i', 'Lagos', 'Locally Used', '2012', '82000km',
        'Automatic', '6850000'],
       dtype='<U67'),
 array(['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', '2013', '39594km',
        'Automatic', '12500000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLE', 'Lagos', 'Foreign Used', '2016', '17299km',
        'Automatic', '36800000'],
       dtype='<U67'),
 array(['Lexus RX 400h', 'Lagos', 'Foreign Used', '2010', '64000km',
        'Automatic', '5900000'],
       dtype='<U67'),
 array(['Toyota Highlander V6', 'Lagos', 'Foreign Used', '2013', '45726km',
        'Automatic', '9500000'],
       dtype='<U67'),
 array(['Mercedes-Benz C300', 'Lagos', 'Foreign Used', '2008', '119115km',
        'Automatic', '5500000'],
       dtype='<U67'),
 array(['Cadillac Escalade', 'Lagos', 'Foreign Used', '2015', '53726km',
        'Automatic', '28000000'],
       dtype='<U67'),
 array(['Toyota Corolla 1.8', 'Lagos', 'Brand New', '2017', '1600km',
        'Automatic', '11500000'],
       dtype='<U67'),
 array(['Land Rover Range Rover Vogue', 'Lagos', 'Locally Used', '2014',

In [126]:
np_new_data

array([['Volkswagen LT', 'Lagos', 'Foreign Used', ..., '280000km',
        'Manual', '2000000'],
       ['Acura MDX Sport Package', 'Rivers', 'Locally Used', ...,
        '143000km', 'Automatic', '3500000'],
       ['Lexus ES 350', 'Delta', 'Foreign Used', ..., '119000km',
        'Automatic', '4400000'],
       ...,
       ['Honda Accord', 'Lagos', 'Foreign Used', ..., '75345km',
        'Automatic', '2900000'],
       ['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', ..., '63563km',
        'Automatic', '4650000'],
       ['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', ..., '62331km',
        'Automatic', '5400000']],
      dtype='<U67')

In [130]:
for i in range(len(new_data)):
    new_data[i][4] = new_data[i][4][:-2]

In [140]:
for i in range(len(new_data)):
    new_data[i][4] = int(new_data[i][4])

In [143]:
myFile = open('new_cars_data.csv', 'w', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(new_data)

In [144]:
np.array([1,2,4])

array([1, 2, 4])

In [145]:
# >>> le = preprocessing.LabelEncoder()
# >>> le.fit(["paris", "paris", "tokyo", "amsterdam"])
# LabelEncoder()
# >>> list(le.classes_)
# ['amsterdam', 'paris', 'tokyo']
# >>> le.transform(["tokyo", "tokyo", "paris"]) 
# array([2, 2, 1]...)
# >>> list(le.inverse_transform([2, 2, 1]))
# ['tokyo', 'tokyo', 'paris']

In [171]:
price = []
for i in range(len(new_data)):
    price.append(int(new_data[i][6]))

In [173]:
# name_of_cars
# location
# condition
# year - int
# mileage - int
# transmission
# price - int

In [235]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

le.fit(name_of_cars)

LabelEncoder()

In [246]:
# tran_name
# tran_location
# tran_condition
# tran_transmission
le.inverse_transform(626)

'Volkswagen LT'

In [261]:
import numpy as np
from sklearn import linear_model

_name,_location,_condition,_year,_mileage,_trans,Y = np.genfromtxt('car_data_final.csv', delimiter=',', dtype=int, unpack=True)

# Combining the X values
# TODO Convert intent and expression to ordinal data
X =  np.column_stack((_name,_location,_condition,_year,_mileage,_trans))

# Training the Model
reg = linear_model.LinearRegression()
reg.fit (X, Y)
reg.coef_

array([ -2.16558395e+03,   3.54670127e+05,  -3.14991822e+06,
         1.11556027e+06,  -7.52747811e-01,   4.71648640e+06])

In [263]:
reg.predict([[4,18,2,2007,143000,0]])

array([ 4192453.512043])